keyVaultName: ssr-o-gp4jqffo3heda
keyVaultIdentity: 00d77036-c127-4b38-a581-f170b55d65f0

nodepool: cccssront01
host: ssr-o.azure.amsterdam.nl

secrets:
  certificate:
    keyVaultName: shared-o-ftytfsr6vuduo
