version: '3.5'
services:
  app: # NGINX
    build:
      context: .
    environment:
      - TZ=Europe/Amsterdam
    image: ${REGISTRY:-localhost:15000}/${REPOSITORY:-sensorenregister/frontend}:${VERSION:-latest}
    ports:
      - '3000:80'

  dev:
    build:
      context: .
      target: builder
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run start
    ports:
      - '3000:3000'

  test-unit:
    build:
      context: .
      target: test
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test
