services:
  app: # NGINX
    build:
      context: .
    environment:
      - TZ=Europe/Amsterdam
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-opdrachten/sensorenregister-frontend}:${VERSION:-latest}
    ports:
      - '3000:8000'

  dev:
    build:
      context: .
      target: base
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run start
    ports:
      - '3000:3000'

  test-unit:
    build:
      context: .
      target: test
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test

  upgrade:
    build:
      context: .
      target: upgrade
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: ncu -u --doctor --target minor
