name: ssr

tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: opdrachten/sensorenregister-frontend
  tag: latest

labels:
  app: sensorenregister

network:
  allow-ingress:
    selector: app == 'sensorenregister'
    ingress:
      - action: Allow
    egress:
      - action: Allow

secrets:
  certificate:
    type: keyvault
    tls: sensorenregister

jobs:
  certificate-init:
    annotations:
      helm.sh/hook: post-install,post-upgrade
    labels:
      component: certificate
    secrets:
      - certificate
    containers:
      - name: main
        command:
          - sleep
        args:
          - '1'

deployments:
  app:
    selectorLabels:
      component: app
    autoscale:
      cpu: 70
    resources:
      requests:
        cpu: 256m
        memory: '512Mi'
      limits:
        cpu: 1
        memory: '512Mi'
    volumes:
      - name: logs
        spec:
          emptyDir: {}
      - name: run
        spec:
          emptyDir: {}
      - name: cache
        spec:
          emptyDir: {}
    containers:
      - name: main
        ports:
          - port: 8000
            name: http
        volumes:
          - name: logs
            mountPath: /var/log/nginx
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx

services:
  app:
    selector:
      component: app
    ports:
      - port: 8000
        targetPort: http

ingress:
  app-external:
    className: nginx-external
    paths:
      - path: /
        pathType: Prefix
        service: app
        port: 8000
    tls: certificate

  app-internal:
    className: nginx-internal
    paths:
      - path: /
        pathType: Prefix
        service: app
        port: 8000
    tls: certificate
