name: ssr

tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: sensorenregister/frontend
  tag: latest

labels:
  app: sensorenregister

network:
  allow-ingress:
    selector: app == 'sensorenregister'
    ingress:
      - action: Allow
    egress:
      - action: Allow

secrets:
  certificate:
    type: keyvault
    tls: sensorenregister

jobs:
  certificate-init:
    labels:
      component: certificate
    mountSecrets:
      - certificate
    command:
      - bash
    args:
      - -c
      - |
        ls -lah /mnt/secrets/certificate
        openssl x509 -in /mnt/secrets/certificate/sensorenregister.crt -text

deployments:
  app:
    selectorLabels:
      component: app
    resources:
      requests:
        cpu: 1
        memory: '512Mi'
      limits:
        cpu: 1
        memory: '512Mi'
    ports:
      - port: 8000
        name: http
    volumes:
      - name: logs
        mountPath: /var/log/nginx
        spec:
          emptyDir: {}
      - name: run
        mountPath: /var/run
        spec:
          emptyDir: {}
      - name: cache
        mountPath: /var/cache/nginx
        spec:
          emptyDir: {}

services:
  app:
    selector:
      component: app
    ports:
      - port: 8000
        targetPort: http

ingress:
  frontend-external:
    className: nginx-external
    paths:
      - path: /
        pathType: Prefix
        service: app
        port: 8000
    tls: certificate

  frontend-internal:
    className: nginx-internal
    paths:
      - path: /
        pathType: Prefix
        service: app
        port: 8000
    tls: certificate
