trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - '*.*.*'

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: tamm/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ssr-frontend
    dev:
      pool: TAMM
      namespace: ns-ccc-ssr-ont-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-ssr-ont-01-sensorenregister
    test:
      variables:
        ENV: test
      pool: TAMM
      namespace: ns-ccc-ssr-tst-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-ssr-tst-01-sensorenregister
    acc:
      variables:
        ENV: acc
      pool: TAMM
      namespace: ns-ccc-ssr-acc-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-ssr-acc-01-sensorenregister
