trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - '*.*.*'

parameters:
  - name: versionOverride
    displayName: "[OPTIONAL] Build/deploy version override"
    type: string
    default: ' '

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: sensorenregister-frontend
    ${{ if ne(parameters.versionOverride, ' ') }}:
      version: ${{ parameters.versionOverride }}
    build:
      producedImages:
      - opdrachten/sensorenregister-frontend
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-ont-01-sensorenregister
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-tst-01-sensorenregister
    acc:
      pool: Opdrachten
      namespace: ns-ccc-opdr-acc-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-acc-01-sensorenregister
    prod:
      pool: Opdrachten
      namespace: ns-ccc-opdr-prd-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-prd-01-sensorenregister
