trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - '*.*.*'

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: tamm/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ssr-frontend
    dev:
      serviceConnection: ARM-CCC-SSR-ont-01
      deploy:
        pool: TAMM
        namespace: ns-ccc-ssr-ont-01-sensorenregister
        kubernetesServiceConnection: SCN-K8S-ns-ccc-ssr-ont-01-sensorenregister
        preSteps:
          - script: helm env
            displayName: helm env
          - script: helm list
            displayName: helm list
          - script: helm history frontend
            displayName: helm history
          - script: helm status frontend
            displayName: helm status
          - script: helm get all frontend
            displayName: helm get all
    test:
      serviceConnection: ARM-CCC-SSR-test-01
      deploy:
        variables:
          ENV: test
        pool: TAMM
        namespace: ns-ccc-ssr-tst-01-sensorenregister
        kubernetesServiceConnection: SCN-K8S-ns-ccc-ssr-tst-01-sensorenregister
