image:
  registry: localhost:5000

# Default host for the ingress resources
host: localhost

network:
  allow-ingress:
    enabled: false

jobs:
  certificate-init:
    enabled: false

ingress:
  app-external:
    enabled: false
  app-internal:
    className: nginx
    tls: null

# Specify the keyvault that has the certificate
secrets:
  certificate:
    enabled: false
