# Default keyvault for getting secrets
keyVaultName: ssr-p-qcczjdu7seqow

# Managed identity (clientId) for workload identity with
workloadIdentity: f2ab4f24-9327-4496-bd57-9fe967d87d5f

# We must select the nodepool to run the pods on
nodepool: cccssrprd01

# Default host for the ingress resources
host: ssr.azure.amsterdam.nl

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-p-3pkvqbyjo6py2
