# Default keyvault for getting secrets
keyVaultName: ssr-t-zryvqlwvrfmge

# Identity AppID (clientId) used to authenticate with the keyvault
keyVaultIdentity: d1a45eca-b417-4da4-8603-32a8e7291591

# We must select the nodepool to run the pods on
nodepool: cccssrtst01

# Default host for the ingress resources
host: ssr-t.azure.amsterdam.nl

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-t-vfstn5vergsqw
